"use client";

import React, { useState } from "react";

interface PdfExportProps {
  planAvailable: boolean;
}

export default function PdfExport({ planAvailable }: PdfExportProps) {
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = async () => {
    if (!planAvailable || isExporting) return;

    setIsExporting(true);

    try {
      // Dynamic import to avoid SSR issues
      const { default: jsPDF } = await import("jspdf");
      const { default: html2canvas } = await import("html2canvas");

      const element = document.getElementById("itinerary-content");
      if (!element) {
        alert("No itinerary content found to export.");
        setIsExporting(false);
        return;
      }

      document.body.classList.add("exporting-pdf");
      // Capture the itinerary element as a canvas
      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        backgroundColor: "#0a0a1a",
        logging: false,
      });

      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "a4");

      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const margin = 10;
      const contentWidth = pdfWidth - 2 * margin;

      // Scale image to fit page width
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;
      const ratio = contentWidth / imgWidth;
      const scaledHeight = imgHeight * ratio;

      // Add cover page
      pdf.setFillColor(10, 10, 26);
      pdf.rect(0, 0, pdfWidth, pdfHeight, "F");

      pdf.setTextColor(99, 102, 241);
      pdf.setFontSize(28);
      pdf.text("Travel Plan", pdfWidth / 2, 60, { align: "center" });

      pdf.setTextColor(160, 160, 192);
      pdf.setFontSize(12);
      pdf.text("Generated by Multi-Agent Travel Planner", pdfWidth / 2, 75, { align: "center" });
      pdf.text(`Exported on ${new Date().toLocaleDateString()}`, pdfWidth / 2, 85, { align: "center" });

      pdf.setTextColor(107, 107, 141);
      pdf.setFontSize(9);
      pdf.text("Powered by Google ADK • A2A Protocol • FastMCP", pdfWidth / 2, pdfHeight - 20, { align: "center" });

      // Add content pages
      let yOffset = 0;
      let pageNumber = 2;

      while (yOffset < scaledHeight) {
        pdf.addPage();

        // Calculate source area for this page
        const srcY = yOffset / ratio;
        const srcHeight = Math.min((pdfHeight - 2 * margin) / ratio, imgHeight - srcY);
        const destHeight = srcHeight * ratio;

        // Create a cropped canvas for this page
        const cropCanvas = document.createElement("canvas");
        cropCanvas.width = imgWidth;
        cropCanvas.height = srcHeight;
        const ctx = cropCanvas.getContext("2d");
        if (ctx) {
          ctx.drawImage(canvas, 0, srcY, imgWidth, srcHeight, 0, 0, imgWidth, srcHeight);
        }

        pdf.setFillColor(10, 10, 26);
        pdf.rect(0, 0, pdfWidth, pdfHeight, "F");

        const cropImgData = cropCanvas.toDataURL("image/png");
        pdf.addImage(cropImgData, "PNG", margin, margin, contentWidth, destHeight);

        // Page number
        pdf.setTextColor(107, 107, 141);
        pdf.setFontSize(8);
        pdf.text(`Page ${pageNumber}`, pdfWidth - margin, pdfHeight - 5, { align: "right" });

        yOffset += pdfHeight - 2 * margin;
        pageNumber++;
      }

      pdf.save("travel-plan.pdf");
    } catch (error: any) {
      console.error("PDF export failed:", error);
      alert(`PDF export failed: ${error.message}`);
    } finally {
      document.body.classList.remove("exporting-pdf");
      setIsExporting(false);
    }
  };

  return (
    <button
      className={`btn btn-secondary btn-sm export-btn ${isExporting ? "exporting" : ""}`}
      onClick={handleExport}
      disabled={!planAvailable || isExporting}
      title={planAvailable ? "Export as PDF" : "Generate a plan first"}
    >
      {isExporting ? (
        <>
          <div className="spinner" style={{ width: 14, height: 14 }} />
          <span>Exporting...</span>
        </>
      ) : (
        <>
          <span>📄</span>
          <span>Export PDF</span>
        </>
      )}

      <style jsx>{`
        .export-btn {
          white-space: nowrap;
        }
        .exporting {
          opacity: 0.7;
        }
      `}</style>
    </button>
  );
}
